on: [push]
jobs:
  lint-exercises:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check chapters && ruff format chapters --check
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8
